packages:
  - apps/*
  - packages/*

allowBuilds:
  "@parcel/watcher": false
  "@swc/core": false
  "@prisma/engines": true
  prisma: true
  sharp: true
  unrs-resolver: false
  esbuild: set this to true or false
