import "server-only"

import { createHash, randomUUID } from "node:crypto"
import { createReadStream } from "node:fs"
import { mkdir, rename, rm, stat, writeFile } from "node:fs/promises"
import path from "node:path"
import { Readable } from "node:stream"

import { env } from "@/server/env"

export const MAX_UPLOAD_BYTES = 15 * 1024 * 1024

export type FileType = { mime: string; ext: string; image: boolean }

/**
 * The real type from the file's first bytes ("magic numbers"). The name and the
 * browser-provided type are never trusted: a renamed .exe or .html is rejected.
 */
export function detectFileType(bytes: Uint8Array): FileType | null {
  const starts = (sig: number[], offset = 0) => sig.every((b, i) => bytes[offset + i] === b)
  if (starts([0xff, 0xd8, 0xff])) return { mime: "image/jpeg", ext: "jpg", image: true }
  if (starts([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))
    return { mime: "image/png", ext: "png", image: true }
  if (starts([0x52, 0x49, 0x46, 0x46]) && starts([0x57, 0x45, 0x42, 0x50], 8))
    return { mime: "image/webp", ext: "webp", image: true }
  if (starts([0x25, 0x50, 0x44, 0x46, 0x2d]))
    return { mime: "application/pdf", ext: "pdf", image: false }
  return null
}

const STORED_NAME =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|png|webp|pdf)$/

function resolveStored(storedName: string) {
  // Stored names are generated by us; anything else (e.g. "../") is refused.
  if (!STORED_NAME.test(storedName)) throw new Error("invalid stored name")
  return path.join(env.UPLOAD_DIR, storedName.slice(0, 2), storedName)
}

/** Writes atomically (temp file + rename) so a crash never leaves a half file. */
export async function saveUpload(bytes: Uint8Array, type: FileType) {
  const storedName = `${randomUUID()}.${type.ext}`
  const target = resolveStored(storedName)
  await mkdir(path.dirname(target), { recursive: true })
  const temp = `${target}.${process.pid}.tmp`
  await writeFile(temp, bytes, { flag: "wx", mode: 0o640 })
  await rename(temp, target)
  return { storedName, sha256: createHash("sha256").update(bytes).digest("hex") }
}

export async function deleteUpload(storedName: string) {
  await rm(resolveStored(storedName), { force: true })
}

export async function openUpload(storedName: string) {
  const file = resolveStored(storedName)
  const { size } = await stat(file)
  return { size, stream: Readable.toWeb(createReadStream(file)) as ReadableStream<Uint8Array> }
}
